# Generated by Django 3.1.4 on 2020-12-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('cover_image', models.FileField(blank=True, max_length=50, upload_to='')),
                ('project_category', models.CharField(blank=True, max_length=50)),
                ('project_client', models.CharField(blank=True, max_length=50)),
                ('project_date', models.DateField(blank=True, max_length=50)),
                ('project_url', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
