# Generated by Django 3.1.4 on 2020-12-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandev_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_category',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('app', 'app')], max_length=50),
        ),
    ]
