# Generated by Django 3.1.4 on 2020-12-23 02:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sandev_app', '0003_clientfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDetails',
            new_name='ProjectDetail',
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='Country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
