# Generated by Django 3.1.4 on 2020-12-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandev_app', '0004_auto_20201223_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
